steps:
  - label: ":git: Clone repository"
    command:
      - "source /var/www/rails-app/Ruby-Website/.env"
      - "git config --global credential helper cache"
      - "git clone https://${GITHUB_USERNAME}:${GITHUB_PAT}@github.com/chock-cho/Ruby-Website.git /var/www/rails-app/Ruby-Website" 
    agents:
      queue: "default"

  - label: ":bundle: Install dependencies"
    command:
      - "cd /var/www/rails-app/Ruby-Website && bundle install"
    agents:
      queue: "default"

  - label: ":database: Database migration"
    command:
      - "cd /var/www/rails-app/Ruby-Website && RAILS_ENV=production rails db:migrate"
    agents:
      queue: "default"

  - label: ":rocket: Deploy to Production"
    command:
      - "cd /var/www/rails-app/Ruby-Website && ./deploy.sh"
    branches: "main"
    agents:
      queue: "default"
